let firstName = `Prabu`;
console.log("The value of firstname is : " +firstName);
console.log("The datatype of firstname is " +typeof firstName);
let companyName = `TestLeaf`;
console.log("The value of companyName is : " +companyName);
console.log("The datatype of companyName is " +typeof companyName);
let mobileNumber = 99999999;
console.log("The value of mobileNumber is : " +mobileNumber);
console.log("The datatype of mobileNumber is " +typeof mobileNumber);
let isAutomation = true;
console.log("The value of isAutomation is : " +isAutomation);
console.log("The datatype of isAutomation is " +typeof isAutomation);
let hasPlaywright;
console.log("The value of hasPlaywright is : " +hasPlaywright);
console.log("The datatype of hasPlaywright is " +typeof hasPlaywright);
let landLine = null;
console.log("The value of landLine is : " +landLine);
console.log("The datatype of landLine is " +typeof landLine);
